let DATA = null;
let selectedDoc = null;
const $ = (sel) => document.querySelector(sel);
const el = (tag, cls, html) => { const n = document.createElement(tag); if (cls) n.className = cls; if (html !== undefined) n.innerHTML = html; return n; };
function md(text){ if(!text) return ""; const html = window.marked ? marked.parse(text,{mangle:false,headerIds:false}) : text.replace(/\n/g,"<br>"); return window.DOMPurify ? DOMPurify.sanitize(html) : html; }
function fmtDate(s){ if(!s) return ""; try{return new Date(s).toLocaleString()}catch{return s} }
function pct(v){ if(v===null||v===undefined||Number.isNaN(v)) return "—"; return `${v>=0?"+":""}${Number(v).toFixed(2)}%`; }
function money(v){ if(v===null||v===undefined||Number.isNaN(v)) return "—"; return Number(v).toLocaleString(undefined,{maximumFractionDigits:2,minimumFractionDigits:2}); }
function quoteColor(q){ return (q.changePct||0) >= 0 ? "up" : "down"; }
function quoteByTicker(t){ return (DATA.quotes||[]).find(q => q.ticker === String(t||"").toUpperCase()); }
function sparkline(values, cls=""){ if(!values||values.length<2) return `<svg class="spark ${cls}" viewBox="0 0 120 42"><path d="M0 22 L120 22"/></svg>`; const min=Math.min(...values), max=Math.max(...values), span=max-min||1; const pts=values.map((v,i)=>{const x=(i/(values.length-1))*120; const y=38-((v-min)/span)*34; return `${i?"L":"M"}${x.toFixed(1)} ${y.toFixed(1)}`}).join(" "); return `<svg class="spark ${cls}" viewBox="0 0 120 42" preserveAspectRatio="none"><path d="${pts}"/></svg>`; }
function quoteCard(q){ const color=quoteColor(q); if(q.error) return `<div class="quote-card"><div class="quote-top"><span class="ticker">${q.ticker}</span><span class="price">n/a</span></div><div class="quote-time">${q.error}</div></div>`; return `<div class="quote-card ${color}"><div class="quote-top"><span class="ticker">${q.ticker}</span><span class="price">${money(q.price)}</span></div><div class="change ${color}">${pct(q.changePct)}</div>${sparkline(q.sparkline,color)}<div class="quote-time">${q.exchange||""} · ${q.quoteTime?fmtDate(q.quoteTime):"snapshot"}</div></div>`; }
function topQuotes(n=8){ return [...(DATA.quotes||[])].filter(q=>!q.error&&q.changePct!==null&&q.changePct!==undefined).sort((a,b)=>Math.abs(b.changePct)-Math.abs(a.changePct)).slice(0,n); }
async function load(){ if(window.__SITE_DATA__) DATA=window.__SITE_DATA__; else DATA=await (await fetch("data/site-data.json",{cache:"no-store"})).json(); selectedDoc=DATA.latestCioNote||DATA.docs[0]; renderShell(); renderOverview(); renderTape(); renderScorecard(); renderAlerts(); renderFiles(); }
function renderShell(){ $("#generated").textContent=`Generated ${fmtDate(DATA.meta.generatedAt)} · ${DATA.stats.quotes||0} quote snapshots · public-safe export`; document.querySelectorAll(".nav button").forEach(btn=>btn.onclick=()=>switchView(btn.dataset.view)); $("#search").addEventListener("input",renderFileList); $("#copyLink").onclick=async()=>{await navigator.clipboard.writeText(location.href); $("#copyLink").textContent="Copied"; setTimeout(()=>$("#copyLink").textContent="Copy dashboard link",1200)}; renderFileList(); }
function switchView(view){ document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view)); document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===view)); window.scrollTo({top:0,behavior:"smooth"}); }
function renderFileList(){ const q=$("#search").value.toLowerCase().trim(); const list=$("#fileList"); list.innerHTML=""; DATA.docs.filter(d=>!q||[d.title,d.category,d.source,d.summary,d.content].join(" ").toLowerCase().includes(q)).slice(0,60).forEach(d=>{const item=el("div","file-item",`<strong>${d.title}</strong><span>${d.category} · ${d.source}</span>`); item.onclick=()=>{selectedDoc=d; renderFiles(); switchView("files")}; list.appendChild(item);}); }
function renderOverview(){ const root=$("#overview"); root.innerHTML=""; root.appendChild(el("div","ticker-strip",topQuotes(8).map(quoteCard).join(""))); const stats=el("div","grid cols-4"); [["Names",DATA.stats.scorecardNames],["Watch",DATA.stats.watchlistNames],["Docs",DATA.stats.docs],["Alerts",DATA.stats.alerts]].forEach(([label,val])=>stats.appendChild(el("div","card",`<div class="stat">${val}</div><div class="muted">${label}</div>`))); root.appendChild(stats); const note=DATA.latestCioNote; root.appendChild(el("article","card markdown",`<h3>Latest CIO Note</h3>${md(note?note.content:"No CIO note yet.")}`)); }
function renderTape(){ const root=$("#tape"); const quotes=[...(DATA.quotes||[])].sort((a,b)=>(a.ticker||"").localeCompare(b.ticker||"")); root.innerHTML=`<div class="card"><h3>Market Tape</h3><p class="muted">Static quote/candle snapshots embedded at build time. Refreshes when the local dashboard job runs.</p><div class="ticker-strip">${topQuotes(10).map(quoteCard).join("")}</div></div><div class="tape">${quotes.map(quoteCard).join("")}</div>`; }
function renderScorecard(){ const root=$("#scorecard"); const rows=DATA.scorecard||[]; root.innerHTML=`<div class="card"><h3>Active Sleeve Scorecard</h3><div class="score-grid">${rows.map(r=>{const q=quoteByTicker(r.Name); return `<article class="score-card"><h4>${r.Name||""}</h4><div class="muted">${r.Theme||""}</div>${q?`<div class="quote-top"><span class="price">${money(q.price)}</span><span class="change ${quoteColor(q)}">${pct(q.changePct)}</span></div>${sparkline(q.sparkline,quoteColor(q))}`:""}<p><span class="label">Stance</span><br>${r["Current desk stance"]||""}</p><p><span class="label">Add only if</span><br>${r["Add only if"]||""}</p><p><span class="label">Risk-reduce if</span><br>${r["Risk-reduce / avoid if"]||""}</p><p><span class="label">Next check</span><br>${r["Next catalyst/check"]||""}</p></article>`}).join("")}</div></div>`; }
function renderAlerts(){ const root=$("#alerts"); root.innerHTML=""; const grid=el("div","grid"); (DATA.latestAlerts||[]).forEach(a=>{const maxLevel=Math.max(0,...a.levels.map(x=>x.level)); grid.appendChild(el("article",`card alert level-${maxLevel} markdown`,md(a.content)))}); if(!DATA.latestAlerts.length) grid.appendChild(el("div","card muted","No recent alerts.")); root.appendChild(grid); }
function renderFiles(){ const root=$("#files"); if(!selectedDoc) selectedDoc=DATA.docs[0]; const grouped=DATA.docs.reduce((acc,d)=>{(acc[d.category]||=[]).push(d); return acc},{}); root.innerHTML=`<div class="grid cols-2"><div class="card"><h3>Document Library</h3>${Object.entries(grouped).map(([cat,docs])=>`<h4>${cat}</h4><div class="pill-row">${docs.map(d=>`<button class="doc-picker" data-doc="${d.id}">${d.title}</button>`).join("")}</div>`).join("")}</div><article class="card markdown"><div class="doc-header"><div><h3>${selectedDoc.title}</h3><div class="doc-meta">${selectedDoc.category} · ${selectedDoc.source} · ${fmtDate(selectedDoc.updated)}</div></div></div>${md(selectedDoc.content)}</article></div>`; root.querySelectorAll(".doc-picker").forEach(btn=>btn.onclick=()=>{selectedDoc=DATA.docs.find(d=>d.id===btn.dataset.doc); renderFiles()}); }
load().catch(err=>{document.body.innerHTML=`<pre style="color:white;padding:24px">Dashboard failed to load: ${err.stack||err}</pre>`});
